const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.Tilemap,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{bg_fase2_devagar_1: 0},
	{bg_fase2_devagar: 0},
	{bg_fase2_medio: 0},
	{bg_fase2_medio1: 0},
	{bg_fase2_medio2: 0},
	{bg_fase2_rapido: 0},
	{bg_fase2_rapido1: 0},
	{bg_devagar: 0},
	{bg_devagar1: 0},
	{bg_medio: 0},
	{bg_rapido: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Touch: 0},
	{BalaoHistoria: 0},
	{BTNProximo: 0},
	{Cutscene1: 0},
	{Cutscene2: 0},
	{Cutscene3: 0},
	{Cutscene4: 0},
	{Cutscene5: 0},
	{Cutscene6: 0},
	{TXTHistoria: 0},
	{BTNDireita: 0},
	{BTNEsquerda: 0},
	{BTNPular: 0},
	{BTNAtaque: 0},
	{FundoMenu: 0},
	{BTNJogar: 0},
	{LogoProjeto: 0},
	{BTNPausa: 0},
	{BTNVoltarJogo: 0},
	{BTNVoltarMenuInicial: 0},
	{MenuPausa: 0},
	{Direcao: 0},
	{VidaMonstroCaixa: 0},
	{Platform: 0},
	{Flash: 0},
	{Caixa: 0},
	{PodeTomarDano: 0},
	{Estado: 0},
	{TempoNoPortal: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Guaxinim: 0},
	{VidaMonstroLampada: 0},
	{PodeAtacar: 0},
	{Lampada: 0},
	{Pin: 0},
	{LampadaArea: 0},
	{AssistentePlanta: 0},
	{SensorCaixaDireita: 0},
	{SensorCaixaEsquerda: 0},
	{Sólido: 0},
	{Espinho: 0},
	{ColetadoFragmento: 0},
	{Fragmento: 0},
	{Limbo: 0},
	{NaveEspacial: 0},
	{ParticulasCaminhada: 0},
	{ParticulasMobs: 0},
	{ParticulasSalto: 0},
	{PodeAtivar: 0},
	{Portal: 0},
	{Solid: 0},
	{PlataformaSolida: 0},
	{TilemapFrente: 0},
	{TilemapFrente2: 0},
	{Coletado: 0},
	{Moeda: 0},
	{Tween: 0},
	{TransicaoCirculo: 0},
	{TransicaoEscuro: 0},
	{FundoPretoTutorial: 0},
	{AssistenteTutorial: 0},
	{BTNProximoTutorial: 0},
	{BalaoTutorial: 0},
	{TXTutorial: 0},
	{BTNPularTutorial: 0},
	{BTNEsquerdaTutorial: 0},
	{BTNDireitaTutorial: 0},
	{BTNAtaqueTutorial: 0},
	{HudVidaTutorial: 0},
	{MoedaTutorial: 0},
	{FragmentoTutorial: 0},
	{CaixaTutorial: 0},
	{LampadaTutorial: 0},
	{TXTFragmentosTutorial: 0},
	{TXTMoedasTutorial: 0},
	{FragmentosTotalTutorial: 0},
	{PainelMissaoTutorial: 0},
	{MissaoAbertaTutorial: 0},
	{HudVida: 0},
	{TXTMoedas: 0},
	{Âncora: 0},
	{MoedaTotal: 0},
	{FundoPreto: 0},
	{FragmentosTotal: 0},
	{TXTFragmentos: 0},
	{PainelMissao: 0},
	{MissaoAberta: 0},
	{Vidas: 0},
	{Moedas: 0},
	{Fragmentos: 0},
	{pausado: 0},
	{Tutorial: 0},
	{Dialogo: 0},
	{FaseAtual: 0},
	{Historia: 0},
	{NumCena: 0},
	{TransicaoIniciar: 0},
	{IniciarJogo: 0},
	{TransicaoTerminar: 0},
	{Vidas2: 0},
	{Moedas2: 0},
	{Fragmentos2: 0},
	{pausado2: 0},
	{Tutorial2: 0},
	{Dialogo2: 0},
	{FaseAtual2: 0}
];

self.InstanceType = {
	bg_fase2_devagar_1: class extends self.ISpriteInstance {},
	bg_fase2_devagar: class extends self.ISpriteInstance {},
	bg_fase2_medio: class extends self.ISpriteInstance {},
	bg_fase2_medio1: class extends self.ISpriteInstance {},
	bg_fase2_medio2: class extends self.ISpriteInstance {},
	bg_fase2_rapido: class extends self.ISpriteInstance {},
	bg_fase2_rapido1: class extends self.ISpriteInstance {},
	bg_devagar: class extends self.ISpriteInstance {},
	bg_devagar1: class extends self.ISpriteInstance {},
	bg_medio: class extends self.ISpriteInstance {},
	bg_rapido: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BalaoHistoria: class extends self.ISpriteInstance {},
	BTNProximo: class extends self.ISpriteInstance {},
	Cutscene1: class extends self.ISpriteInstance {},
	Cutscene2: class extends self.ISpriteInstance {},
	Cutscene3: class extends self.ISpriteInstance {},
	Cutscene4: class extends self.ISpriteInstance {},
	Cutscene5: class extends self.ISpriteInstance {},
	Cutscene6: class extends self.ISpriteInstance {},
	TXTHistoria: class extends self.ITextInstance {},
	BTNDireita: class extends self.ISpriteInstance {},
	BTNEsquerda: class extends self.ISpriteInstance {},
	BTNPular: class extends self.ISpriteInstance {},
	BTNAtaque: class extends self.ISpriteInstance {},
	FundoMenu: class extends self.ISpriteInstance {},
	BTNJogar: class extends self.ISpriteInstance {},
	LogoProjeto: class extends self.ISpriteInstance {},
	BTNPausa: class extends self.ISpriteInstance {},
	BTNVoltarJogo: class extends self.ISpriteInstance {},
	BTNVoltarMenuInicial: class extends self.ISpriteInstance {},
	MenuPausa: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Guaxinim: class extends self.ISpriteInstance {},
	Lampada: class extends self.ISpriteInstance {},
	LampadaArea: class extends self.ISpriteInstance {},
	AssistentePlanta: class extends self.ISpriteInstance {},
	SensorCaixaDireita: class extends self.ISpriteInstance {},
	SensorCaixaEsquerda: class extends self.ISpriteInstance {},
	Espinho: class extends self.ISpriteInstance {},
	Fragmento: class extends self.ISpriteInstance {},
	Limbo: class extends self.ISpriteInstance {},
	NaveEspacial: class extends self.ISpriteInstance {},
	ParticulasCaminhada: class extends self.IParticlesInstance {},
	ParticulasMobs: class extends self.IParticlesInstance {},
	ParticulasSalto: class extends self.IParticlesInstance {},
	Portal: class extends self.ISpriteInstance {},
	PlataformaSolida: class extends self.ISpriteInstance {},
	TilemapFrente: class extends self.ITilemapInstance {},
	TilemapFrente2: class extends self.ITilemapInstance {},
	Moeda: class extends self.ISpriteInstance {},
	TransicaoCirculo: class extends self.ISpriteInstance {},
	TransicaoEscuro: class extends self.ISpriteInstance {},
	FundoPretoTutorial: class extends self.ISpriteInstance {},
	AssistenteTutorial: class extends self.ISpriteInstance {},
	BTNProximoTutorial: class extends self.ISpriteInstance {},
	BalaoTutorial: class extends self.ISpriteInstance {},
	TXTutorial: class extends self.ITextInstance {},
	BTNPularTutorial: class extends self.ISpriteInstance {},
	BTNEsquerdaTutorial: class extends self.ISpriteInstance {},
	BTNDireitaTutorial: class extends self.ISpriteInstance {},
	BTNAtaqueTutorial: class extends self.ISpriteInstance {},
	HudVidaTutorial: class extends self.ISpriteInstance {},
	MoedaTutorial: class extends self.ISpriteInstance {},
	FragmentoTutorial: class extends self.ISpriteInstance {},
	CaixaTutorial: class extends self.ISpriteInstance {},
	LampadaTutorial: class extends self.ISpriteInstance {},
	TXTFragmentosTutorial: class extends self.ITextInstance {},
	TXTMoedasTutorial: class extends self.ITextInstance {},
	FragmentosTotalTutorial: class extends self.ISpriteInstance {},
	PainelMissaoTutorial: class extends self.ISpriteInstance {},
	MissaoAbertaTutorial: class extends self.ISpriteInstance {},
	HudVida: class extends self.ISpriteInstance {},
	TXTMoedas: class extends self.ITextInstance {},
	MoedaTotal: class extends self.ISpriteInstance {},
	FundoPreto: class extends self.ISpriteInstance {},
	FragmentosTotal: class extends self.ISpriteInstance {},
	TXTFragmentos: class extends self.ITextInstance {},
	PainelMissao: class extends self.ISpriteInstance {},
	MissaoAberta: class extends self.ISpriteInstance {}
}