const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Tilemap_fundo: 0},
	{PodeTomarDano: 0},
	{Estado: 0},
	{TempoNoPortal: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Flash: 0},
	{Timer: 0},
	{Guaxinim: 0},
	{Solid: 0},
	{Sendor_Solido: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{BTNDireita: 0},
	{BTNEsquerda: 0},
	{BTNPular: 0},
	{Touch: 0},
	{Sprite2: 0},
	{Direcao: 0},
	{VidaMonstroCaixa: 0},
	{CAIXA_PATRULHEIRO: 0},
	{Coletado: 0},
	{Âncora: 0},
	{Moeda: 0},
	{Sensor_Caixa_Direita: 0},
	{Sensor_Caixa_Esquerda: 0},
	{HUD_VIDA: 0},
	{PodeAtivar: 0},
	{PORTAL: 0},
	{Pontos: 0},
	{MoedaTotal: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{ColetadoFragmento: 0},
	{Fragmento: 0},
	{Inimigo_Lampada: 0},
	{bg_nuvem: 0},
	{Sprite6: 0},
	{bg_chao: 0},
	{Tilemap_frente: 0},
	{Sólido: 0},
	{ESPINHO: 0},
	{Limbo: 0},
	{Background_: 0},
	{Background_2: 0},
	{Vidas: 0},
	{Moedas: 0},
	{Fragmentos: 0}
];

self.InstanceType = {
	Tilemap_fundo: class extends self.ITilemapInstance {},
	Guaxinim: class extends self.ISpriteInstance {},
	Sendor_Solido: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BTNDireita: class extends self.ISpriteInstance {},
	BTNEsquerda: class extends self.ISpriteInstance {},
	BTNPular: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	CAIXA_PATRULHEIRO: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Sensor_Caixa_Direita: class extends self.ISpriteInstance {},
	Sensor_Caixa_Esquerda: class extends self.ISpriteInstance {},
	HUD_VIDA: class extends self.ISpriteInstance {},
	PORTAL: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	MoedaTotal: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Fragmento: class extends self.ISpriteInstance {},
	Inimigo_Lampada: class extends self.ISpriteInstance {},
	bg_nuvem: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bg_chao: class extends self.ISpriteInstance {},
	Tilemap_frente: class extends self.ITilemapInstance {},
	ESPINHO: class extends self.ISpriteInstance {},
	Limbo: class extends self.ISpriteInstance {},
	Background_: class extends self.ISpriteInstance {},
	Background_2: class extends self.ISpriteInstance {}
}